# Generated by Django 5.2.3 on 2025-07-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='gpu_usage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
